import type {
  Lead, Invoice, Appointment, Conversation, Message,
  KnowledgeBaseEntry, Notification, DashboardMetrics, PriorityItem, Business
} from "./types";

// ─── MOCK BUSINESS ───────────────────────────────────────────────────────────
export const mockBusiness: Business = {
  id: "biz-001",
  name: "Apex Consulting Group",
  industry: "Business Consulting",
  website: "https://apexconsulting.com",
  phone: "+1 (555) 234-5678",
  email: "hello@apexconsulting.com",
  plan: "PRO",
  timezone: "America/New_York",
  aiPersonaName: "Alex",
  aiPersonaGreeting: "Hi there! I'm Alex from Apex Consulting. How can I help you today?",
  createdAt: "2025-01-15T08:00:00Z",
};

// ─── MOCK LEADS ───────────────────────────────────────────────────────────────
export const mockLeads: Lead[] = [
  {
    id: "lead-001",
    businessId: "biz-001",
    name: "Sarah Mitchell",
    email: "sarah.mitchell@techcorp.com",
    phone: "+1 (555) 987-6543",
    status: "HOT",
    source: "Website Widget",
    budget: 15000,
    need: "Full business strategy overhaul and operational efficiency audit",
    timeline: "Q1 2026",
    lastContact: "2026-09-27T09:15:00Z",
    createdAt: "2026-09-25T14:30:00Z",
    conversationId: "conv-001",
    score: 92,
    tags: ["enterprise", "urgent", "high-value"],
  },
  {
    id: "lead-002",
    businessId: "biz-001",
    name: "James Okafor",
    email: "james@startupflow.io",
    phone: "+1 (555) 234-8765",
    status: "HOT",
    source: "Referral",
    budget: 8500,
    need: "Go-to-market strategy and investor pitch preparation",
    timeline: "Next 30 days",
    lastContact: "2026-09-27T07:45:00Z",
    createdAt: "2026-09-24T10:00:00Z",
    conversationId: "conv-002",
    score: 87,
    tags: ["startup", "funding", "pitch"],
  },
  {
    id: "lead-003",
    businessId: "biz-001",
    name: "Priya Sharma",
    email: "priya.sharma@retailplus.com",
    phone: "+1 (555) 345-6789",
    status: "WARM",
    source: "LinkedIn",
    budget: 5000,
    need: "Retail expansion strategy for 3 new locations",
    timeline: "Q2 2026",
    lastContact: "2026-09-26T16:20:00Z",
    createdAt: "2026-09-22T09:15:00Z",
    conversationId: "conv-003",
    score: 68,
    tags: ["retail", "expansion"],
  },
  {
    id: "lead-004",
    businessId: "biz-001",
    name: "Marcus Chen",
    email: "m.chen@financewave.com",
    phone: "+1 (555) 456-7890",
    status: "WARM",
    source: "Google Ads",
    budget: 12000,
    need: "Financial process optimization and compliance audit",
    timeline: "Q1 2026",
    lastContact: "2026-09-25T11:00:00Z",
    createdAt: "2026-09-21T13:45:00Z",
    conversationId: "conv-004",
    score: 71,
    tags: ["finance", "compliance"],
  },
  {
    id: "lead-005",
    businessId: "biz-001",
    name: "Elena Rodriguez",
    email: "elena@healthbridge.org",
    phone: "+1 (555) 567-8901",
    status: "COLD",
    source: "Website Widget",
    budget: 3000,
    need: "Non-profit operational restructuring",
    timeline: "H2 2026",
    lastContact: "2026-09-20T14:00:00Z",
    createdAt: "2026-09-18T10:30:00Z",
    conversationId: "conv-005",
    score: 34,
    tags: ["non-profit", "long-term"],
  },
  {
    id: "lead-006",
    businessId: "biz-001",
    name: "David Thompson",
    email: "d.thompson@logistix.com",
    phone: "+1 (555) 678-9012",
    status: "COLD",
    source: "Cold Outreach",
    budget: 2000,
    need: "Supply chain assessment",
    timeline: "Unspecified",
    lastContact: "2026-09-15T09:00:00Z",
    createdAt: "2026-09-14T08:00:00Z",
    conversationId: "conv-006",
    score: 22,
    tags: ["logistics"],
  },
];

// ─── MOCK CONVERSATIONS ───────────────────────────────────────────────────────
export const mockConversations: Conversation[] = [
  {
    id: "conv-001",
    businessId: "biz-001",
    leadId: "lead-001",
    leadName: "Sarah Mitchell",
    leadEmail: "sarah.mitchell@techcorp.com",
    lastMessage: "That sounds perfect. When can we schedule a discovery call?",
    lastMessageAt: "2026-09-27T09:15:00Z",
    status: "ACTIVE",
    aiHandled: true,
    createdAt: "2026-09-25T14:30:00Z",
    messages: [
      {
        id: "msg-001",
        conversationId: "conv-001",
        sender: "CUSTOMER",
        senderName: "Sarah Mitchell",
        content: "Hi, I'm looking for a consulting firm that can help us do a full operational overhaul. We're a 200-person tech company struggling with efficiency.",
        createdAt: "2026-09-25T14:30:00Z",
        isRead: true,
      },
      {
        id: "msg-002",
        conversationId: "conv-001",
        sender: "AI",
        senderName: "Alex (AI)",
        content: "Hi Sarah! Thanks for reaching out to Apex Consulting. A full operational overhaul for a 200-person tech company is exactly what we specialize in. Could you tell me a bit more about your main pain points? And do you have a timeline or budget in mind?",
        createdAt: "2026-09-25T14:31:00Z",
        isRead: true,
        agentAction: "Greeted customer, gathering qualification data",
      },
      {
        id: "msg-003",
        conversationId: "conv-001",
        sender: "CUSTOMER",
        senderName: "Sarah Mitchell",
        content: "We're wasting about 30% of productivity on redundant processes. Budget is around $15k and we'd like to start Q1 2026.",
        createdAt: "2026-09-25T14:35:00Z",
        isRead: true,
      },
      {
        id: "msg-004",
        conversationId: "conv-001",
        sender: "AI",
        senderName: "Alex (AI)",
        content: "A $15,000 budget for an operational audit and overhaul is well within our Pro package range. With a Q1 start, we'd have time to do a thorough discovery and deliver a full action plan before year-end. Our typical engagement includes a 2-week audit, stakeholder interviews, and a prioritized efficiency roadmap. Would you like me to schedule a discovery call with our lead consultant?",
        createdAt: "2026-09-25T14:36:00Z",
        isRead: true,
        agentAction: "Lead qualified as HOT (budget: $15k, timeline: Q1, need: operational overhaul). Score: 92",
      },
      {
        id: "msg-005",
        conversationId: "conv-001",
        sender: "CUSTOMER",
        senderName: "Sarah Mitchell",
        content: "That sounds perfect. When can we schedule a discovery call?",
        createdAt: "2026-09-27T09:15:00Z",
        isRead: false,
      },
    ],
  },
  {
    id: "conv-002",
    businessId: "biz-001",
    leadId: "lead-002",
    leadName: "James Okafor",
    leadEmail: "james@startupflow.io",
    lastMessage: "I've got an investor meeting in 3 weeks. This is urgent.",
    lastMessageAt: "2026-09-27T07:45:00Z",
    status: "ACTIVE",
    aiHandled: true,
    createdAt: "2026-09-24T10:00:00Z",
    messages: [
      {
        id: "msg-006",
        conversationId: "conv-002",
        sender: "CUSTOMER",
        senderName: "James Okafor",
        content: "Hey, I need help putting together a Series A pitch deck and GTM strategy. We're a B2B SaaS startup.",
        createdAt: "2026-09-24T10:00:00Z",
        isRead: true,
      },
      {
        id: "msg-007",
        conversationId: "conv-002",
        sender: "AI",
        senderName: "Alex (AI)",
        content: "Hey James! Series A pitch prep is one of our most popular services. We've helped 20+ startups close their rounds. What's your current ARR and target raise amount?",
        createdAt: "2026-09-24T10:02:00Z",
        isRead: true,
        agentAction: "Engaged with startup pitch request, gathering financials",
      },
      {
        id: "msg-008",
        conversationId: "conv-002",
        sender: "CUSTOMER",
        senderName: "James Okafor",
        content: "ARR is $180k, targeting $2M raise. Budget for consulting is around $8,500. I've got an investor meeting in 3 weeks. This is urgent.",
        createdAt: "2026-09-27T07:45:00Z",
        isRead: false,
      },
    ],
  },
];

// ─── MOCK INVOICES ────────────────────────────────────────────────────────────
export const mockInvoices: Invoice[] = [
  {
    id: "inv-001",
    businessId: "biz-001",
    leadId: "lead-001",
    clientName: "Sarah Mitchell",
    clientEmail: "sarah.mitchell@techcorp.com",
    number: "INV-2026-001",
    status: "OVERDUE",
    items: [
      { id: "item-001", description: "Operational Audit Phase 1", quantity: 1, unitPrice: 5000, total: 5000 },
      { id: "item-002", description: "Stakeholder Interview Sessions (5 sessions)", quantity: 5, unitPrice: 800, total: 4000 },
      { id: "item-003", description: "Efficiency Roadmap Document", quantity: 1, unitPrice: 2000, total: 2000 },
    ],
    subtotal: 11000,
    tax: 880,
    total: 11880,
    dueDate: "2026-09-20T00:00:00Z",
    sentAt: "2026-09-05T10:00:00Z",
    viewedAt: "2026-09-06T14:22:00Z",
    notes: "Payment due within 15 days of invoice date. Late fees may apply after due date.",
    createdAt: "2026-09-05T09:30:00Z",
    followUpCount: 2,
  },
  {
    id: "inv-002",
    businessId: "biz-001",
    leadId: "lead-003",
    clientName: "Priya Sharma",
    clientEmail: "priya.sharma@retailplus.com",
    number: "INV-2026-002",
    status: "SENT",
    items: [
      { id: "item-004", description: "Retail Expansion Feasibility Study", quantity: 1, unitPrice: 3500, total: 3500 },
      { id: "item-005", description: "Market Analysis Report", quantity: 1, unitPrice: 1500, total: 1500 },
    ],
    subtotal: 5000,
    tax: 400,
    total: 5400,
    dueDate: "2026-10-15T00:00:00Z",
    sentAt: "2026-09-25T09:00:00Z",
    notes: "",
    createdAt: "2026-09-24T15:00:00Z",
    followUpCount: 0,
  },
  {
    id: "inv-003",
    businessId: "biz-001",
    clientName: "Marcus Chen",
    clientEmail: "m.chen@financewave.com",
    number: "INV-2026-003",
    status: "PAID",
    items: [
      { id: "item-006", description: "Financial Process Audit", quantity: 1, unitPrice: 6000, total: 6000 },
      { id: "item-007", description: "Compliance Review", quantity: 1, unitPrice: 3000, total: 3000 },
      { id: "item-008", description: "Implementation Support (10 hrs)", quantity: 10, unitPrice: 150, total: 1500 },
    ],
    subtotal: 10500,
    tax: 840,
    total: 11340,
    dueDate: "2026-09-10T00:00:00Z",
    sentAt: "2026-08-26T11:00:00Z",
    viewedAt: "2026-08-27T09:15:00Z",
    paidAt: "2026-09-08T16:30:00Z",
    notes: "Thank you for your prompt payment!",
    createdAt: "2026-08-25T14:00:00Z",
    followUpCount: 1,
  },
  {
    id: "inv-004",
    businessId: "biz-001",
    clientName: "James Okafor",
    clientEmail: "james@startupflow.io",
    number: "INV-2026-004",
    status: "DRAFT",
    items: [
      { id: "item-009", description: "Series A Pitch Deck Creation", quantity: 1, unitPrice: 5000, total: 5000 },
      { id: "item-010", description: "Go-to-Market Strategy Document", quantity: 1, unitPrice: 3500, total: 3500 },
    ],
    subtotal: 8500,
    tax: 680,
    total: 9180,
    dueDate: "2026-10-27T00:00:00Z",
    notes: "Rush delivery included at no additional charge.",
    createdAt: "2026-09-27T08:00:00Z",
    followUpCount: 0,
  },
];

// ─── MOCK APPOINTMENTS ────────────────────────────────────────────────────────
export const mockAppointments: Appointment[] = [
  {
    id: "apt-001",
    businessId: "biz-001",
    leadId: "lead-002",
    clientName: "James Okafor",
    clientEmail: "james@startupflow.io",
    clientPhone: "+1 (555) 234-8765",
    title: "Series A Strategy Discovery Call",
    description: "Initial discovery session to understand funding goals, current metrics, and pitch deck requirements.",
    status: "CONFIRMED",
    startTime: "2026-09-27T15:00:00Z",
    endTime: "2026-09-27T16:00:00Z",
    meetingUrl: "https://meet.google.com/abc-defg-hij",
    reminderSent: true,
    createdAt: "2026-09-25T10:00:00Z",
  },
  {
    id: "apt-002",
    businessId: "biz-001",
    leadId: "lead-004",
    clientName: "Marcus Chen",
    clientEmail: "m.chen@financewave.com",
    title: "Financial Compliance Review Kickoff",
    description: "Kickoff meeting for the Q4 compliance audit engagement.",
    status: "CONFIRMED",
    startTime: "2026-09-28T14:00:00Z",
    endTime: "2026-09-28T15:30:00Z",
    meetingUrl: "https://zoom.us/j/987654321",
    reminderSent: false,
    createdAt: "2026-09-24T11:00:00Z",
  },
  {
    id: "apt-003",
    businessId: "biz-001",
    clientName: "Elena Rodriguez",
    clientEmail: "elena@healthbridge.org",
    title: "Non-Profit Strategy Consultation",
    description: "Initial consultation for operational restructuring needs.",
    status: "NO_SHOW",
    startTime: "2026-09-26T10:00:00Z",
    endTime: "2026-09-26T11:00:00Z",
    meetingUrl: "https://meet.google.com/xyz-uvwx-yz",
    reminderSent: true,
    createdAt: "2026-09-20T14:00:00Z",
  },
  {
    id: "apt-004",
    businessId: "biz-001",
    leadId: "lead-003",
    clientName: "Priya Sharma",
    clientEmail: "priya.sharma@retailplus.com",
    title: "Retail Expansion Planning Workshop",
    status: "PENDING",
    startTime: "2026-10-02T13:00:00Z",
    endTime: "2026-10-02T15:00:00Z",
    location: "Apex Consulting Office, Suite 400",
    reminderSent: false,
    createdAt: "2026-09-26T09:00:00Z",
  },
];

// ─── MOCK KNOWLEDGE BASE ─────────────────────────────────────────────────────
export const mockKnowledgeBase: KnowledgeBaseEntry[] = [
  {
    id: "kb-001",
    businessId: "biz-001",
    question: "What consulting services do you offer?",
    answer: "We offer four core service areas: (1) Operational Efficiency Audits — identifying and eliminating process waste, (2) Go-to-Market Strategy — for startups launching new products, (3) Financial Process Optimization — streamlining financial operations and compliance, and (4) Organizational Restructuring — for businesses scaling or pivoting. All engagements include a kickoff discovery session and a final deliverable report.",
    category: "Services",
    isActive: true,
    usageCount: 47,
    createdAt: "2026-01-15T08:00:00Z",
    updatedAt: "2026-09-01T10:00:00Z",
  },
  {
    id: "kb-002",
    businessId: "biz-001",
    question: "How much do your services cost?",
    answer: "Our pricing depends on engagement scope: Starter audits begin at $3,000 for small businesses. Our Pro engagements range from $5,000–$15,000 for mid-market companies. Enterprise retainers start at $20,000+/month. We offer a free 30-minute discovery call before any commitment. We do not offer hourly rates; all engagements are project-based.",
    category: "Pricing",
    isActive: true,
    usageCount: 89,
    createdAt: "2026-01-15T08:00:00Z",
    updatedAt: "2026-09-15T14:00:00Z",
  },
  {
    id: "kb-003",
    businessId: "biz-001",
    question: "How long does a typical engagement last?",
    answer: "Engagement length varies by service: Operational Audits: 3–6 weeks. GTM Strategy: 4–8 weeks. Financial Optimization: 2–4 weeks. Full Retainer: Ongoing, typically 3–12 months. All timelines include a kickoff, working sessions, and final delivery.",
    category: "Process",
    isActive: true,
    usageCount: 34,
    createdAt: "2026-02-01T08:00:00Z",
    updatedAt: "2026-08-20T10:00:00Z",
  },
  {
    id: "kb-004",
    businessId: "biz-001",
    question: "Do you work with startups?",
    answer: "Absolutely. We have a dedicated Startup Track for early-stage companies. Services include pitch deck preparation, investor narrative building, market sizing, and product-market fit validation. We've helped 20+ startups close funding rounds ranging from $500K to $5M. Special startup pricing is available for pre-revenue companies.",
    category: "Services",
    isActive: true,
    usageCount: 61,
    createdAt: "2026-02-10T08:00:00Z",
    updatedAt: "2026-09-10T12:00:00Z",
  },
  {
    id: "kb-005",
    businessId: "biz-001",
    question: "Are your consultants industry-specific?",
    answer: "Yes. Our team includes specialists in tech, retail, finance, healthcare, and logistics. When you book a discovery call, we match you with the consultant best suited to your industry. Our lead consultants average 12+ years of industry experience.",
    category: "Team",
    isActive: true,
    usageCount: 28,
    createdAt: "2026-03-01T08:00:00Z",
    updatedAt: "2026-08-01T10:00:00Z",
  },
  {
    id: "kb-006",
    businessId: "biz-001",
    question: "What is your refund policy?",
    answer: "We offer a 100% satisfaction guarantee on our initial discovery audit. If you're not satisfied with the diagnostic report, we'll refund the initial payment in full within 7 business days. Project-based engagements are non-refundable after the kickoff session, but we commit to delivering agreed-upon milestones.",
    category: "Policy",
    isActive: true,
    usageCount: 12,
    createdAt: "2026-03-15T08:00:00Z",
    updatedAt: "2026-07-01T10:00:00Z",
  },
];

// ─── MOCK NOTIFICATIONS ───────────────────────────────────────────────────────
export const mockNotifications: Notification[] = [
  {
    id: "notif-001",
    businessId: "biz-001",
    type: "LEAD",
    title: "New HOT Lead: James Okafor",
    body: "Series A pitch prep request — $8,500 budget, 3-week urgency. AI has engaged.",
    isRead: false,
    priority: "HIGH",
    relatedId: "lead-002",
    createdAt: "2026-09-27T07:46:00Z",
  },
  {
    id: "notif-002",
    businessId: "biz-001",
    type: "INVOICE",
    title: "Invoice Overdue: INV-2026-001",
    body: "Sarah Mitchell's invoice for $11,880 is 7 days overdue. AI sent 2 follow-ups.",
    isRead: false,
    priority: "HIGH",
    relatedId: "inv-001",
    createdAt: "2026-09-27T06:00:00Z",
  },
  {
    id: "notif-003",
    businessId: "biz-001",
    type: "APPOINTMENT",
    title: "No-Show: Elena Rodriguez",
    body: "Missed the 10:00 AM consultation. AI has sent a reschedule offer automatically.",
    isRead: false,
    priority: "MEDIUM",
    relatedId: "apt-003",
    createdAt: "2026-09-26T11:05:00Z",
  },
  {
    id: "notif-004",
    businessId: "biz-001",
    type: "AI_ACTION",
    title: "AI Qualified New Lead",
    body: "Sarah Mitchell classified as HOT lead (score: 92). Budget $15K confirmed.",
    isRead: true,
    priority: "MEDIUM",
    relatedId: "lead-001",
    createdAt: "2026-09-25T14:36:00Z",
  },
  {
    id: "notif-005",
    businessId: "biz-001",
    type: "INVOICE",
    title: "Payment Received: INV-2026-003",
    body: "Marcus Chen paid $11,340 on September 8. Revenue updated.",
    isRead: true,
    priority: "LOW",
    relatedId: "inv-003",
    createdAt: "2026-09-08T16:35:00Z",
  },
];

// ─── MOCK DASHBOARD METRICS ───────────────────────────────────────────────────
export const mockDashboardMetrics: DashboardMetrics = {
  leadsThisWeek: 4,
  leadsLastWeek: 2,
  hotLeads: 2,
  avgResponseTime: "1m 24s",
  revenuePending: 17280, // inv-001 + inv-002
  revenueCollected: 11340, // inv-003
  appointmentsToday: 1,
  overdueInvoices: 1,
};

// ─── MOCK PRIORITY ITEMS ──────────────────────────────────────────────────────
export const mockPriorityItems: PriorityItem[] = [
  {
    id: "pri-001",
    type: "LEAD",
    priority: "HIGH",
    title: "James Okafor needs immediate response",
    description: "$8,500 pitch prep deal — investor meeting in 3 weeks",
    actionLabel: "View Conversation",
    relatedId: "conv-002",
    urgency: "NOW",
  },
  {
    id: "pri-002",
    type: "INVOICE",
    priority: "HIGH",
    title: "INV-2026-001 is 7 days overdue",
    description: "Sarah Mitchell owes $11,880 — escalation recommended",
    actionLabel: "View Invoice",
    relatedId: "inv-001",
    urgency: "NOW",
  },
  {
    id: "pri-003",
    type: "APPOINTMENT",
    priority: "MEDIUM",
    title: "Elena Rodriguez no-showed",
    description: "Re-engage before lead goes cold",
    actionLabel: "Send Re-engage",
    relatedId: "apt-003",
    urgency: "TODAY",
  },
  {
    id: "pri-004",
    type: "APPOINTMENT",
    priority: "MEDIUM",
    title: "Marcus Chen meeting tomorrow",
    description: "Compliance review kickoff at 2:00 PM — no reminder sent yet",
    actionLabel: "Send Reminder",
    relatedId: "apt-002",
    urgency: "TODAY",
  },
];

// ─── CHART DATA ───────────────────────────────────────────────────────────────
export const weeklyLeadsData = [
  { day: "Mon", leads: 1, hot: 0, warm: 1, cold: 0 },
  { day: "Tue", leads: 0, hot: 0, warm: 0, cold: 0 },
  { day: "Wed", leads: 2, hot: 1, warm: 1, cold: 0 },
  { day: "Thu", leads: 1, hot: 0, warm: 0, cold: 1 },
  { day: "Fri", leads: 3, hot: 2, warm: 1, cold: 0 },
  { day: "Sat", leads: 0, hot: 0, warm: 0, cold: 0 },
  { day: "Sun", leads: 1, hot: 0, warm: 0, cold: 1 },
];

export const revenueData = [
  { month: "Apr", collected: 8200, pending: 3100 },
  { month: "May", collected: 11500, pending: 5200 },
  { month: "Jun", collected: 9800, pending: 4300 },
  { month: "Jul", collected: 14200, pending: 6800 },
  { month: "Aug", collected: 10900, pending: 8100 },
  { month: "Sep", collected: 11340, pending: 17280 },
];

export const leadSourceData = [
  { name: "Website Widget", value: 38, color: "#3B82F6" },
  { name: "Referral", value: 27, color: "#8B5CF6" },
  { name: "LinkedIn", value: 18, color: "#06B6D4" },
  { name: "Google Ads", value: 12, color: "#10B981" },
  { name: "Cold Outreach", value: 5, color: "#64748B" },
];
